### ISSUE TITLE
Social authentication

### ISSUE THREAD

**Issue by Psvensso** [Witf/witf.web#2]
The app should be 'user-aware' and allow the user to login.
This would prepare for later enhancements such as "my recipies".

The app should only allow Facebook and Google social logins.
We then associate that login (SSID) with our login account.

**Comment by michaldog** [comment]
Implemented in `wift.searchengine`. Needs to be moved to the new `witf.backend` repo.

**Comment by mariusin79** [comment]
-> Mangler: hookup frontend with Auth0
	-> Flytte Auth0 koden fra witf.search til witf.backend

**Comment by Psvensso** [comment]
@michaldog I added Facebook to the new backend auth, it comes more or less part of the package. Can you review if that is enough and understandable and if were missing something by not using the Auth0 code.

**Comment by michaldog** [comment]
@Psvensso My knowledge on this subject is thin at best.  You're using OAuth2 (authorization framework), while I've used Auth0 with JWT (authentication protocol and framework agnostic, but partially dependent on 3rd party - albeit free). They can potentially interact, but I'm not sure of the details yet. I have a Auth0 frontend spike, so I will give that a go first.
