### ISSUE TITLE
Fjerne Api gateway i witf.web

### ISSUE THREAD

**Issue by mariusin79** [Witf/witf.web#5]
-> Lage nytt github repo: witf.backend
	-> Endre slik at front bruker nytt api
	-> Witf.web må støtte dev pipeline, dvs enkelt å startes lokalt for å teste web + backend lokalt
	-> Implementeres i dotnet.core
	-> Apiet bli WebApi

**Comment by Psvensso** [comment]
Closing. This issue is only confusing. The api is no longer in .web project.
